# Codecov Configuration
# See: https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch:
      default:
        target: auto
        threshold: 5%
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "node_modules/**/*"
  - "dist/**/*"
  - "build/**/*"
  - "tests/**/*"
  - "*.config.*"
  - "main.js"
  - "version-bump.mjs"
  - ".claude/**/*"
